version: '3'

services:
  app:
    container_name: nextfin
    build:
      context: ../../../
      dockerfile: src/main/docker/Dockerfile
    image:
      nextfin:1.0
    ports:
      - '8080:8080'
    environment:
      - DB_URL=nextfin-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=bankdb
      - DB_PREFS=sslmodde=require
    depends_on:
      - psql-db
  psql-db:
    image: postgres
    container_name: nextfin-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bankdb
    ports:
      - '5432:5432'

