ALTER TABLE TRANSACTIONS
    ADD CONSTRAINT UC_TRANSACTIONS_SOURCE_ACCOUNT UNIQUE (SOURCE_ACCOUNT_ID);

ALTER TABLE TRANSACTIONS
    ADD CONSTRAINT UC_TRANSACTIONS_TARGET_ACCOUNT UNIQUE (TARGET_ACCOUNT_ID);

ALTER TABLE TRANSACTIONS
    ALTER COLUMN AMOUNT TYPE DECIMAL USING (AMOUNT::DECIMAL);

ALTER TABLE ACCOUNTS
    ALTER COLUMN BALANCE TYPE DECIMAL USING (BALANCE::DECIMAL);

ALTER TABLE TRANSACTIONS
    ALTER COLUMN FEE TYPE DECIMAL USING (FEE::DECIMAL);

ALTER TABLE TRANSACTIONS
    ALTER COLUMN UPDATED_AT SET NOT NULL;