ALTER TABLE SPRING_SESSION_ATTRIBUTES
    DROP CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK;

ALTER TABLE USERS
    ADD CONSTRAINT UC_USERS_EMAIL UNIQUE (EMAIL);

ALTER TABLE USERS
    ADD CONSTRAINT UC_USERS_USERNAME UNIQUE (USERNAME);

ALTER TABLE HOLDERS
    ADD CONSTRAINT FK_HOLDERS_ON_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID);

ALTER TABLE USERS
    ADD CONSTRAINT FK_USERS_ON_HOLDER FOREIGN KEY (HOLDER_ID) REFERENCES HOLDERS (ID);

DROP TABLE JOBRUNR_BACKGROUNDJOBSERVERS CASCADE;

DROP TABLE JOBRUNR_JOBS CASCADE;

DROP TABLE JOBRUNR_METADATA CASCADE;

DROP TABLE JOBRUNR_MIGRATIONS CASCADE;

DROP TABLE JOBRUNR_RECURRING_JOBS CASCADE;

DROP TABLE SPRING_SESSION CASCADE;

DROP TABLE SPRING_SESSION_ATTRIBUTES CASCADE;

ALTER TABLE HOLDERS
    DROP COLUMN EMAIL;

ALTER TABLE HOLDERS
    DROP COLUMN PASSWORD;

ALTER TABLE HOLDERS
    DROP COLUMN "social-security-number";

ALTER TABLE HOLDERS
    DROP COLUMN USERNAME;

ALTER SEQUENCE EMPLOYEE_SEQ INCREMENT BY 1;

ALTER SEQUENCE HOLDERS_SEQ INCREMENT BY 1;

ALTER TABLE TRANSACTIONS
    ALTER COLUMN AMOUNT TYPE DECIMAL USING (AMOUNT::DECIMAL);

ALTER TABLE ACCOUNTS
    ALTER COLUMN BALANCE TYPE DECIMAL USING (BALANCE::DECIMAL);

ALTER TABLE TRANSACTIONS
    ALTER COLUMN FEE TYPE DECIMAL USING (FEE::DECIMAL);

ALTER TABLE ADDRESS
    ALTER COLUMN ZIP_CODE TYPE VARCHAR(5) USING (ZIP_CODE::VARCHAR(5));