ALTER TABLE TRANSACTIONS
    ADD SCHEDULED_AT TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE TRANSACTIONS
    ADD TRANSACTION_TYPE SMALLINT;

ALTER TABLE TRANSACTIONS
    ALTER COLUMN TRANSACTION_TYPE SET NOT NULL;

ALTER TABLE USERS
    ADD CONSTRAINT "uc_users_preferred-phone-number" UNIQUE ("preferred-phone-number");