name: Deploy & Release NextFin

on:
  workflow_dispatch:  # Allows manual triggering
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Act Workaround
        if: ${{ env.ACT }}
        run: curl -fsSL https://deb.nodesource.com/setup_22.x | bash && apt install -y nodejs
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Spring Boot application
        run: ./gradlew bootJar -x test

      - name: Bump Version
        id: bump
        uses: Plugily-Projects/version-bump-action@v6
        with:
          github-token: ${{ secrets.github_token }}
          auto-version-bump: true
          repo-build: 'GRADLE'

      - name: Print Version
        run: "echo 'New Version: ${{steps.bump.outputs.version}}'"
      
      - name: Store New Version in GITHUB_ENV
        run: echo "VERSION=${{steps.bump.outputs.version}}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION}}
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
